[package]
name = "brumm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redstone_schem = { git = "https://github.com/StackDoubleFlow/redstone_schem" }
